### PR TITLE
Error and Device status, on/off switch update

### PR DESCRIPTION
**Pull request by enboer**

### CODE REVIEW

**Comment by enboer** [comment]
Added 2 devices, Error/Device Status and on/off button fix

**Comment by Gabo1223** [comment]
Hello, I have a smart home controlled by LOXON and I have heat pump with a 4-pin MODBUS output, I would like to ask you for the MODBUS protocols for this device so that I can integrate it into my system. Thank you very much

**Comment by Gabo1223** [comment]
my e-mail is wiszczor@pbwconcrete.cz pls send me protokols Modbus in excel. thanks

**Comment by enboer** [comment]
Here is the list

<Protocol of Modbus-heat pump.xls>


Erik Nijeboer

Op 29 mrt. 2023 om 20:42 heeft Gabo1223 ***@***.***> het volgende geschreven:

﻿

my e-mail is ***@***.******@***.***> pls send me protokols Modbus in excel. thanks

**Comment by Gabo1223** [comment]
Hello Erik,
thank you very much for your help.

Unfortunately, it seems something along the way removed the attached file. 

I can see only file name in your comment, the attachment (link) is not there.

Could you please try to upload it using github web instead of email?

Thank you!

Gabo

**Comment by enboer** [comment]
Second try.

Erii.

**Comment by Gabo1223** [comment]
sorry, I still don't see the attachment, please can you send me the XLS file directly to the e-mail WISZCZOR@PBWCONCRETE.CZ
Thank you.

**Comment by Gabo1223** [comment]
Hi Erik, thank you in advance for sending the MOD-BUS protocols for the pool heat pump, I already have it integrated into LOXONE.
Now I'm going to do the same thing at a friend's place and he has two heat pumps, and I can't switch the inverter to another address for the MOD-BUS slave control board.
Please advise me. Thank you Gabriel

**Pull request closed without merging**
